package com.csye6225.fall2018.courseservice667.datamodel;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBIndexHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@DynamoDBTable(tableName="board")
public class Board 
{
	private String id; 
	private String boardId; 
	private String courseId; 
	
	public Board() {
		
	}
	
	public Board(String id, String boardId, String courseId) {
		this.id = id;
		this.boardId = boardId; 
		this.courseId = courseId; 
	}
	
	@DynamoDBHashKey(attributeName = "Id")
    @DynamoDBAutoGeneratedKey
	public String getId() {
		return id;
	}

	public void setId(String id) {
		this.id = id;
	}
	

	@DynamoDBIndexHashKey(globalSecondaryIndexName = "Board-BoardId", attributeName="boardId")
	public String getBoardId() {
		return boardId;
	}

	public void setBoardId(String boardId) {
		this.boardId = boardId;
	}

	@DynamoDBAttribute(attributeName="courseId")
	public String getCourseId() {
		return courseId;
	}

	public void setCourseId(String courseId) {
		this.courseId = courseId;
	}
}
