package com.csye6225.fall2018.courseservice667.datamodel;

import java.util.ArrayList;
import java.util.List;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBIgnore;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBIndexHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;


@DynamoDBTable(tableName="student")
public class Student {
	private String id; 
	private String firstName;
	private String lastName; 
	private String department;
	private String studentId;
	private String joiningDate;
	private List<String> registeredCourses = new ArrayList<String>(); 
	
	public Student() {
		
	}
	
	public Student(String id, String studentId, String firstName, String lastName, String department, String joiningDate, 
			List<String> registeredCourses) {
		this.id = id;
		this.studentId = studentId;
		this.firstName = firstName;
		this.lastName = lastName; 
		this.department = department;
		this.joiningDate = joiningDate;
		this.registeredCourses = registeredCourses;
	}
	
	@DynamoDBHashKey(attributeName = "Id")
    @DynamoDBAutoGeneratedKey
	public String getId() {
		return id;
	}

	public void setId(String id) {
		this.id = id;
	}

	
	@DynamoDBAttribute(attributeName="firstName")
	public String getFirstName() {
		return firstName;
	}
	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}
	
	@DynamoDBAttribute(attributeName="lastName")
	public String getLastName() {
		return lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}
	
	@DynamoDBAttribute(attributeName="department")
	public String getDepartment() {
		return department;
	}
	public void setDepartment(String department) {
		this.department = department;
	}

	@DynamoDBIndexHashKey(globalSecondaryIndexName = "Student-StudentId", attributeName="studentId")
	public String getStudentId() {
		return studentId;
	}
	public void setStudentId(String studentId) {
		this.studentId = studentId;
	}
	
	@DynamoDBAttribute(attributeName="joiningDate")
	public String getJoiningDate() {
		return joiningDate;
	}
	public void setJoiningDate(String joiningDate) {
		this.joiningDate = joiningDate;
	}

	@DynamoDBAttribute(attributeName="registeredCourses")
	public List<String> getRegisteredCourses() {
		return registeredCourses;
	}

	public void setRegisteredCourses(List<String> registeredCourses) {
		this.registeredCourses = registeredCourses;
	}
	
	@DynamoDBIgnore
	@Override
	public String toString() { 
		return "StudentId=" + getStudentId() + ", firstName=" + getFirstName()
				+ ", department=" + getDepartment() + ", joiningDate=" + getJoiningDate() + ", registered courses=" 
				+ getRegisteredCourses();
	}

}
