package com.csye6225.fall2018.courseservice667.datamodel;

import java.util.Date;

import javax.xml.bind.annotation.XmlRootElement;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBIgnore;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBIndexHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@DynamoDBTable(tableName="professors")
public class Professor {
	private String id;
	private String firstName;
	private String lastName;
	private String department;
	private String professorId;
	private String joiningDate;
	
	public Professor() {
		
	}
	
	public Professor(String id, String professorId, String firstName, String lastName,String department, String joiningDate) {
		this.id=id;
		this.professorId = professorId;
		this.firstName = firstName;
		this.lastName=lastName;
		this.department = department;
		this.joiningDate = joiningDate;
	}
	
	@DynamoDBHashKey(attributeName="Id")
	@DynamoDBAutoGeneratedKey
	public String getID()
	{
		return id;
	}
	
	public void setID(String id)
	{
		this.id=id;
	}
	
	@DynamoDBAttribute(attributeName="firstName")
	public String getFirstName() {
		return firstName;
	}
	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}
	
	@DynamoDBAttribute(attributeName="lastName")
	public String getLastName() {
		return lastName;
	}
	public void setLastName(String lastName) {
		this.lastName = lastName;
	}
	
	@DynamoDBAttribute(attributeName="department")
	public String getDepartment() {
		return department;
	}
	public void setDepartment(String department) {
		this.department = department;
	}

	@DynamoDBIndexHashKey(globalSecondaryIndexName = "ProfessorID-index", attributeName="professorID")
	public String getProfessorId() {
		return professorId;
	}
	public void setProfessorId(String professorId) {
		this.professorId = professorId;
	}
	
	@DynamoDBAttribute(attributeName="joiningDate")
	public String getJoiningDate() {
		return joiningDate;
	}
	public void setJoiningDate(String joiningDate) {
		this.joiningDate = joiningDate;
	}
	
	@DynamoDBIgnore
	@Override
	public String toString()
	{
		return "ProfID="+getProfessorId()+", firstname="+getFirstName()+", department="+getDepartment()+", joining date="+getJoiningDate();
	}
}
