package com.csye6225.fall2018.courseservice667.datamodel;

import javax.xml.bind.annotation.XmlRootElement;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@XmlRootElement
@DynamoDBTable(tableName="Registrar")
public class Registrar 
{
  private String RegistrationId;
  private String OfferingId;
  private String OfferingType;
  private String Department;
  private float PerUnitPrice;
  
  public Registrar()
  {
	  
  }
  
  public Registrar(String RegistrationId,String OfferingId,String OfferingType,String Department,float PerUnitPrice)
  {
	  this.RegistrationId=RegistrationId;
	  this.OfferingId=OfferingId;
	  this.OfferingType=OfferingType;
	  this.Department=Department;
	  this.PerUnitPrice=PerUnitPrice;
  }
  
  @DynamoDBHashKey(attributeName = "RegistrationId")
  @DynamoDBAutoGeneratedKey
  public String getRegistrationId()
  {
	  return RegistrationId;
  }
  
  public void setRegistrationId(String RegistrationId)
  {
	  this.RegistrationId=RegistrationId;
  }
  
  @DynamoDBAttribute(attributeName = "OfferingId")
  public String getOfferingId()
  {
	  return OfferingId;
  }
  
  public void setOfferingId(String OfferingId)
  {
	  this.OfferingId=OfferingId;
  }
  
  @DynamoDBAttribute(attributeName = "OfferingType")
  public String getOfferingType()
  {
	  return OfferingType;
  }
  
  public void setOfferingType(String OfferingType)
  {
	  this.OfferingType=OfferingType;
  }
  
  @DynamoDBAttribute(attributeName = "Department")
  public String getDepartment()
  {
	  return Department;
  }
  
  public void setDepartment(String Department)
  {
	  this.Department=Department;
  }
  
  @DynamoDBAttribute(attributeName = "PerUnitPrice")
  public float getPerUnitPrice()
  {
	  return PerUnitPrice;
  }
  
  public void setPerUnitPrice(float PerUnitPrice)
  {
	  this.PerUnitPrice=PerUnitPrice;
  }
}
